### ISSUE TITLE
Dealing with laravel storage

### ISSUE THREAD

**Issue by aginev** [jildertmiedema/laravel-plupload#10]
Hello, 

I having some troubles dealing with local storage. As mentioned in L5 docs:

> The put method may be used to store a file on disk. You may also pass a PHP resource to the put method, which will use Flysystem's underlying stream support. Using streams is greatly recommended when dealing with large files:

But at the moment the very last part of the files is written at the storage or just a few KBs

```php
return Plupload::receive('file', function (UploadedFile $file) {
    $storage = Storage::disk('uploads')->put('test.mp3', $file);

    return 'ready';
});
```

Any ideas how to figure out this are very appreciated!

Regards

Nasko

**Comment by jildertmiedema** [comment]
Sorry for the late response. Did you solve this problem already?

**Comment by aginev** [comment]
I think so... it was my mistake.

> $storage = Storage::disk('uploads')->put('test.mp3', $file);

The $file param needs to be the file contents or file resource but I was passing a UploadedFile instance. I didn't manage to create resource from the upload file temp location in the php temp directory that's why I'm storing the file localy and then move it to the selected storage (there are many in my app) like so

```php
return \Plupload::receive('file', function (UploadedFile $file) {
	$unique_filename = 'your_unique_filename_here';
	
	// Move uploaded file
	$file->move(storage_path('/temp/'), $unique_filename);

    // Move to storage
	$storage = Storage::disk('uploads')->put('test.mp3', fopen(storage_path('/temp/' . $unique_filename)));
});
```

Any better solution in your mind?

Regards

Nasko

**Comment by jildertmiedema** [comment]
Support for streams (FlySystem and Laravel Storage) would be nice, but i dont have any recent plans to implement this.

I will close the issue.
