### ISSUE TITLE
Laravel 5.1.25

### ISSUE THREAD

**Issue by lemonCMS** [jildertmiedema/laravel-plupload#11]
Hi!

I'me having the following problem.

When you have the chunksize in plupload on lets say "1mb", then you cannot upload files larger the 1mb for laravel-plupload will not receive the file or something..

There is no error, you just don't get into the nameless function

````php
$return = Plupload::receive('file', function ($file) { 
  //Will not come here when upload is larger then chunksize!
});
````

Running:
nginx - 1.62
````
client_max_body_size 500M;
````
hhvm - 3.6.1
```
upload_max_filesize = 1024M
post_max_size = 1024M
````

Kind regards,
Raymond

**Comment by lemonCMS** [comment]
Pfff After some debugging i figured out it was a fault in my own controller. No idea what changed for it work before.

**Comment by jildertmiedema** [comment]
Thanks for usinging laravel-plupload
