### ISSUE TITLE
uploading as {FileName}.part 

### ISSUE THREAD

**Issue by birkansava** [jildertmiedema/laravel-plupload#12]
I have an issue. It's uploading like {FileName}.part .I've checked php.ini and nothing wrong. I guess there is a problem with : 

`if ($chunk == $chunks - 1) {
                $file = new UploadedFile($filePath, $originalName, 'blob', filesize($filePath), UPLOAD_ERR_OK, true);
                $result = $closure($file);
                @unlink($filePath);
            }`

I think UploadedFile is not working for some reason but I didn't understand. Can you help me ?

**Comment by jildertmiedema** [comment]
I don't have enough information to help you. Do you get an error in your laravel log? Do normal uploads work? How does to html look like...

**Comment by jildertmiedema** [comment]
I can't help you if you don't give any information, therefore i will close the issue.
