### ISSUE TITLE
Stopping upload and selecting another file

### ISSUE THREAD

**Issue by pavlovskyarto** [jildertmiedema/laravel-plupload#13]
Hi!
Im trying to stop current upload and then I select another file and begin upload. Backend just merge this two files. 
How to prevent this?

`upload.stop();
                upload.removeFile(upload.files[0]);
                $('#filelist').html('');
                upload.destroy();
                upload = uploader();
                upload.init();`

**Comment by jildertmiedema** [comment]
I have never worked on this scenario. Maybe we can add a extra label on a upload so we can distinguish this.

**Comment by jildertmiedema** [comment]
Here we can do that i think.
https://github.com/jildertmiedema/laravel-plupload/blob/master/src/JildertMiedema/LaravelPlupload/Receiver.php#L67 

Another solution can be to delete (or not append) the content when `$chunk == 1`, maybe easier to implement.

**Comment by pavlovskyarto** [comment]
`
if($request->get('chunk') == '0') {
                $originalName = $request->get('name');
                $filePath = storage_path().'/plupload/'.$originalName.'.part';
                if (file_exists($filePath) && filemtime($filePath) < time() - 600) {
                    @unlink($filePath);
                }
            }
            return \Plupload::receive('file', function ($file)
            {
                $fileName = str_random(4)."_".$file->getClientOriginalName();
                $file->move(public_path().'/uploads/', $fileName);
                return ['result' => 'ready', 'file' => $fileName];
            });
`

**Comment by jildertmiedema** [comment]
Sorry, can you please reformat your code.

You can send a PR if it works

**Comment by jildertmiedema** [comment]
Were you able to fix the issue?

**Comment by jildertmiedema** [comment]
I consider this a solved
