### ISSUE TITLE
Multiple instances for repeater fields

### ISSUE THREAD

**Issue by mayeenulislam** [jildertmiedema/laravel-plupload#14]
Hi, found this plugin very easy to setup and nicely ready for production. We've made a form for our client with a single attachment block with multiple attachments facilities.

But now client wants to bind Some text/select choice with each of the files individually so that they provide title for each of the file or they can group files etc. So I choose repeater fields with using [jQuery Dynamic Form](https://github.com/nianja/dynamicForm) and Plupload for each of the row. The thing should be something like this:
![dynamic form for repeater fields with plupload](https://cloud.githubusercontent.com/assets/4551598/20788658/e6da56da-b7db-11e6-97fd-370da3c97a71.png)

I found [a solution](http://stackoverflow.com/questions/9269779/how-can-i-add-a-select-field-to-my-plupload-form), I think, not yet tried.

But your plugin might not ready for such things:
1. It's generating UI widget by default and I cannot trigger a Core view for each of the fields
2. You are using id for plupload selector and id selector for iterating fields failed me to select files in newly generated plupload instances

So what I got is:
![dynamic form for repeater fields with plupload](https://cloud.githubusercontent.com/assets/4551598/20788904/b9f8a904-b7dc-11e6-847d-1a6f314facdf.png)

And plupload simply isn't working for multiple instances where it's triggered on an ID.

**Comment by jildertmiedema** [comment]
Maybe you can inject the request like this:

```php

Route::post('/upload', function(\Illuminate\Http\Request $request)
{
    return Plupload::receive('file', function ($file) use ($request)
    {
        $file->move(storage_path() . '/test/', $file->getClientOriginalName());
        $info = $request->get('info');

        //do something with $info

        return 'ready';
    });
});
```
