### ISSUE TITLE
[Suggestion] Use Illuminate\Http\UploadedFile instead of Symfony\Component\HttpFoundation\File\UploadedFile

### ISSUE THREAD

**Issue by Landish** [jildertmiedema/laravel-plupload#15]
Why not use `Illuminate\Http\UploadedFile` instead of `Symfony\Component\HttpFoundation\File\UploadedFile` in [Receiver.php line 7](https://github.com/jildertmiedema/laravel-plupload/blob/master/src/JildertMiedema/LaravelPlupload/Receiver.php#L7)?

With that, you'll have more functions on `$file` instance in the `receive` method of plupload, such as `store`, `storeAs` and etc. https://laravel.com/docs/5.3/filesystem

```php
Route::post('/upload', function()
{
    return Plupload::receive('file', function (UploadedFile $file)
    {
        $file->store('path_to_dir');
        return 'ready';
    });
});
```

I would make a pull request, but, not sure if this package is still under maintenance. 
Plus it's only one line need to be changed and after running unit tests on this package I ended up with errors, which was caused by Mocking in my mind.

**Comment by jildertmiedema** [comment]
When if build te package i had some reasons to do it like this. But i think it it a nice solution. If you send a pull request I will merge it.

**Comment by Landish** [comment]
@jildertmiedema You see, build is failing cause of the error in `testGetDefaultView` test, which has nothing to do with changes, i've made.

**Comment by mahaidong** [comment]
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to JildertMiedema\LaravelPlupload\Receiver::appendData() must be an instance of Illuminate\Http\UploadedFile, instance of Symfony\Component\HttpFoundation\File\UploadedFile given, called in  .../vendor/jildertmiedema/laravel-plupload/src/JildertMiedema/LaravelPlupload/Receiver.php on line 70 in .../vendor/jildertmiedema/laravel-plupload/src/JildertMiedema/LaravelPlupload/Receiver.php:40
