### ISSUE TITLE
Postinit funtion

### ISSUE THREAD

**Issue by xciser77** [jildertmiedema/laravel-plupload#17]
i am trying to get a postinit function in the facade maker, but it escape the function
Plupload::init([
	'init'=> "{PostInit: function() {document.getElementById('filelist').innerHTML = '';document.getElementById('uploadfiles').onclick = function() {uploader.start();return false;};
	}}",

If i remove the "" it fails because, the code is wrong, but how can I implement the Postinit function?

**Comment by jildertmiedema** [comment]
For "complex cases" i would recommend not using the facade, but just build the blade template with the uploader as blade code.
