### ISSUE TITLE
Problem with Laravel 5.1

### ISSUE THREAD

**Issue by jakjr** [jildertmiedema/laravel-plupload#19]
Hello,

This packages depends on "Illuminate\Http\UploadedFile" Class [Receiver.php, appendData()],

but this Laravel Class was only created on Laravel 5.3, so, this packages breaks when used on Laravel 5.1.

I could use this by replacing these files:
LaravelPluploadServiceProvider.php
Manager.php
Receiver.php

On the new Receiver.php I used the "Symfony\Component\HttpFoundation\File\UploadedFile"

Thanks.

**Comment by jildertmiedema** [comment]
I think you should use version 0.3.1 in that case.

**Comment by jakjr** [comment]
True. Thanks.

**Comment by jildertmiedema** [comment]
Maybe the composer file has to be updated to limit this. For now i will close the issue

**Comment by marulitua** [comment]
Hi!
I also have problem with Laravel 5.1.
In composer.lock i already use 0.3.1.
Please help me.

this is from laravel log
`[2017-04-20 01:22:12] local.ERROR: exception 'JildertMiedema\LaravelPlupload\PluploadException' with message 'Failed to open output stream.' in /var/www/dinas/releases/22/vendor/jildertmiedema/laravel-plupload/src/JildertMiedema/LaravelPlupload/Receiver.php:43
Stack trace:
#0 /var/www/dinas/releases/22/vendor/jildertmiedema/laravel-plupload/src/JildertMiedema/LaravelPlupload/Receiver.php(70): JildertMiedema\LaravelPlupload\Receiver->appendData('/var/www/dinas/...', Object(Symfony\Component\HttpFoundation\File\UploadedFile))
#1 /var/www/dinas/releases/22/vendor/jildertmiedema/laravel-plupload/src/JildertMiedema/LaravelPlupload/Receiver.php(102): JildertMiedema\LaravelPlupload\Receiver->receiveChunks('file', Object(Closure))
#2 /var/www/dinas/releases/22/vendor/jildertmiedema/laravel-plupload/src/JildertMiedema/LaravelPlupload/Manager.php(31): JildertMiedema\LaravelPlupload\Receiver->receive('file', Object(Closure))
#3 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(6087): JildertMiedema\LaravelPlupload\Manager->receive('file', Object(Closure))
#4 /var/www/dinas/releases/22/app/Http/Controllers/LampiranController.php(119): Illuminate\Support\Facades\Facade::__callStatic('receive', Array)
#5 /var/www/dinas/releases/22/app/Http/Controllers/LampiranController.php(119): JildertMiedema\LaravelPlupload\Facades\Plupload::receive('file', Object(Closure))
#6 [internal function]: App\Http\Controllers\LampiranController->upload('pembangunan-ged...', 'pekerjaan')
#7 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(8931): call_user_func_array(Array, Array)
#8 /var/www/dinas/releases/22/app/Http/routes.php(105): Illuminate\Routing\Controller->callAction('upload', Array)
#9 [internal function]: App\Providers\RouteServiceProvider->{closure}('pembangunan-ged...')
#10 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(7892): call_user_func_array(Object(Closure), Array)
#11 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(7879): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#12 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(7535): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9651): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 /var/www/dinas/releases/22/app/Http/Middleware/Authenticate.php(45): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9643): call_user_func_array(Array, Array)
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9633): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(7536): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(7524): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(7509): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9651): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9643): call_user_func_array(Array, Array)
#29 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(13002): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9643): call_user_func_array(Array, Array)
#32 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(11594): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9643): call_user_func_array(Array, Array)
#35 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(12739): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9643): call_user_func_array(Array, Array)
#38 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(12676): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9643): call_user_func_array(Array, Array)
#41 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9643): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(9633): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /var/www/dinas/releases/22/bootstrap/cache/compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#48 /var/www/dinas/releases/22/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#49 {main}  

`

**Comment by jildertmiedema** [comment]
Check your write permissions. Please don't put your log files in other issues

**Comment by marulitua** [comment]
thanks @jildertmiedema 
well noted
