### ISSUE TITLE
Can you create a tag from a specific reference please?

### ISSUE THREAD

**Issue by mahmutbayri** [jildertmiedema/laravel-plupload#24]
Hi,

The one of my old project with using laravel 4.2 has been configured as dev-master. 

dev-master version is referenced to 1b85aa6075521549fa8094048c00d5e4dfc5015c, because v0.2.1 version has a few bugs.  I would be happy if it is possible to create  a new tag this reference (https://github.com/jildertmiedema/laravel-plupload/commit/1b85aa6075521549fa8094048c00d5e4dfc5015c) as v0.2.2 or something.

Thanks.

**Comment by jildertmiedema** [comment]
done
