### ISSUE TITLE
PHP 7.2  throw the sizeof warning

### ISSUE THREAD

**Issue by zotopteam** [jildertmiedema/laravel-plupload#26]
When uploadfile under PHP 7.2 ， throw the sizeof warning:

`sizeof(): Parameter must be an array or an object that implements Countable
`

File:

`vendor\jildertmiedema\laravel-plupload\src\JildertMiedema\LaravelPlupload\Receiver.php
`

Line: 73

`$file = new UploadedFile($filePath, $originalName, 'blob', sizeof($filePath), UPLOAD_ERR_OK, true);
`

I found this:

http://www.php.net/count

`7.2.0   count() will now yield a warning on invalid countable types passed to the array_or_countable parameter.`

Waiting Help,Thanks!

**Comment by Fraganya** [comment]
well $filepath seems to be a string so i replaced **strlen**($filepath) with sizeof or count. and it worked for me

**Comment by shaktijs** [comment]
Hi,

It looks like we need "filesize" function instead of "sizeof" to fix this error. I changed this and it works perfectly. If it is correct please add a commit for this.

> vendor\jildertmiedema\laravel-plupload\src\JildertMiedema\LaravelPlupload\Receiver.php

Line: 73

> $file = new UploadedFile($filePath, $originalName, 'blob', sizeof($filePath), UPLOAD_ERR_OK, true);

**Comment by jildertmiedema** [comment]
PR is merged

**Comment by qanvo** [comment]
Hi, 
Please, can you release the git repo, i think you forgot to push tags.
Thanks for your works !
