### ISSUE TITLE
This seems not working on a live server

### ISSUE THREAD

**Issue by muhozi** [jildertmiedema/laravel-plupload#30]
This package seems not working on a live server, but locally it's working. There is no additional info in `laravel.log`

- Laravel version: 5.2
- Laravel-Plupload version: 0.3.1

On a live server I'm using the following:
- Nginx Server(Ubuntu 16.04.4 LTS) - Digital Ocean
- PHP Version: 7.0

Locally, I'm using the following:
- Nginx Server(Laravel valet)
- PHP Version: 7.0

I did all necessary configurations on the server including setting max file upload size and max post size in php.ini. I also set max client body size.

**Comment by jildertmiedema** [comment]
Sorry i cannot help you with this. 

I close the ticket
