### ISSUE TITLE
Problem with UploadedFile from Symfony new Http-Foundation 

### ISSUE THREAD

**Issue by jakjr** [jildertmiedema/laravel-plupload#35]
The construct of UploadFile do not accept the filesize anymore.

So, the method receiveChunks should instance the new UploadedFile, without passing the filesize attribute:
$file = new UploadedFile($filePath, $originalName, 'blob', UPLOAD_ERR_OK, true); /*sizeof => filesize : fix for php 7.2*/

**Comment by m33ts4k0z** [comment]
Hi,

Can you please add a pull request with this fix to the repo?

**Comment by jakjr** [comment]
@m33ts4k0z Done.
