### ISSUE TITLE
Issue "unknown error" While Uploading image in laravel 8

### ISSUE THREAD

**Issue by imhsgoraya** [jildertmiedema/laravel-plupload#38]
Symfony\Component\HttpFoundation\File\Exception\FileException: The file "image.png" was not uploaded due to an unknown error. in file /var/www/html/laravel_common_web/vendor/symfony/http-foundation/File/UploadedFile.php on line 213

i am uploading right extension image and right size image which we have specified.

can you help to get what's the error

**Comment by restyler** [comment]
I confirm the same issue in Laravel 8.

**Comment by jakjr** [comment]
The construct of UploadFile do not accept the filesize anymore.

So, the method receiveChunks should instance the new UploadedFile, without passing the filesize attribute:
$file = new UploadedFile($filePath, $originalName, 'blob', UPLOAD_ERR_OK, true); /sizeof => filesize : fix for php 7.2/

**Comment by alariva** [comment]
@jakjr Affirmative, it works :rocket:

**Comment by m33ts4k0z** [comment]
@jakjr Please add a pull request with this fix to the repo so it can get baked into the source.

**Comment by jagers** [comment]
This issue should be closed since it was fixed via https://github.com/jildertmiedema/laravel-plupload/pull/41
