### ISSUE TITLE
Error #-200: HTTP Error.

### ISSUE THREAD

**Issue by iwasherefirst2** [jildertmiedema/laravel-plupload#39]
Locally, this pluploader works fine. On my prod server it works for files less then 1 MB, for everything else it fails like this:

![image](https://user-images.githubusercontent.com/1765602/123762583-3dae7d80-d8c3-11eb-834e-662f434d0724.png)

Although it shows 100% in the progressbar, same named files are available in plupload folder, but they have size 0kb.

This is how it looks in inspection window:
![image](https://user-images.githubusercontent.com/1765602/123763315-eeb51800-d8c3-11eb-82fa-c2a68026d9c3.png)

**Comment by jildertmiedema** [comment]
i think this is a server side setting
