### ISSUE TITLE
Incomplete attachment to the original file

### ISSUE THREAD

**Issue by shahrestani** [jildertmiedema/laravel-plupload#40]
If you send a file in pieces and there is a problem in the middle of the work and the submission is incomplete, a part file will be stored on the server.
Now, if you send the file completely again, it will connect the pieces in the server section, and in addition to the pieces of the original file, the incomplete piece that already exists will be added to the file, and the length of the file will be longer than the original file.

**Comment by jildertmiedema** [comment]
Expired
