### ISSUE TITLE
Laravel 5.0 Support

### ISSUE THREAD

**Issue by stevebauman** [jildertmiedema/laravel-plupload#6]
Any thought's on updating this package for 5.0? Looking through your code, I don't see any dependency issues using `illuminate/support: ~5.0` over `4.2`. Is allowing installation of this package with either versions possible through composer? I know Laravel 5.0 is in it's infancy at the moment, but I'd definitely like to try this package out with it.

**Comment by jildertmiedema** [comment]
I did some updates to support laravel 5. https://github.com/jildertmiedema/laravel-plupload/tree/v0.3.0

**Comment by stevebauman** [comment]
Great thanks!
